---
- name: Install Gitlab Server
  hosts: gitlab-server
  become: true
  vars:
    gitlab_root_password: Abcd1234!

  roles:
    - geerlingguy.gitlab

  tasks:
    - name: Open port 80 and 443
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
      loop:
        - http
        - https
      notify: Reload firewalld
      tags: firewalld

    - name: Copy self-signed certificate
      ansible.builtin.fetch:
        src: /etc/gitlab/ssl/gitlab.crt
        dest: /home/vagrant/
        # Stores the file at /home/vagrant/gitlab-server/etc/gitlab/ssl/gitlab.crt
      tags: fetch

  handlers:
    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
